name: Demo call workflow calling demo workflow
on:
 push:
  branches: [main]

jobs:

 democall:
  runs-on: ubuntu-latest
  steps:
   - name: calling demo workflow
     uses: ./.github/workflows/demo.yml
